### ISSUE TITLE
Catalog -> Catalog support

### ISSUE THREAD

**Issue by mattfung** [planetlabs/staccato#5]
Hello,

I'm wondering if staccato currently supports subcatalogs that reside in catalogs Catalog -> Catalog?
To my knowledge, the Items schema supports subcatalogs, but that only implements Item -> Catalog.

best

**Comment by joshfix** [comment]
Hi @mattfung.  Staccato does currently support a concept of subcatalogs.  There is a bit of documentation in the readme:

https://github.com/planetlabs/staccato#custom-annotations

You can see this annotation in use in the [Landsat8 collection](https://github.com/planetlabs/staccato/blob/master/staccato-collections/landsat8/src/main/java/com/planet/staccato/landsat8/Landsat8.java#L17-L29) and on the reference deployment where you can traverse down row/path subcatalogs:

https://stac.boundlessgeo.io/stac/landsat-8-l1/landsat:wrs_path/165/landsat:wrs_row/57

**Comment by mattfung** [comment]
Thanks for the info. The docs were helpful.
