### ISSUE TITLE
Search API Request with Point Intersect returns error

### ISSUE THREAD

**Issue by mattfung** [planetlabs/staccato#6]
### Expected behaviour

Search Requests with well formed Point intersect data should return filtered objects.

Example JSON payload for `/stac/search` request
```
{
        ...
	"intersects":  { 
		"type": "Point", 
		"coordinates": [100.0, 0.0] 
	}
}
```
### Current behaviour

Error is returned 400 error due to type cast error

```
{
       "code": "400",
       "description": "class java.util.ArrayList cannot be cast to class [D (java.util.ArrayList and [D are in module java.base of loader 'bootstrap')"
}
```

**Comment by joshfix** [comment]
Thanks again for the contributions @mattfung!
