### ISSUE TITLE
Support for open date intervals

### ISSUE THREAD

**Issue by mattfung** [planetlabs/staccato#8]
### Expected Behaviour

Based on stac-spec, one should be able to query for open date intervals using the `..` symbol.
https://github.com/radiantearth/stac-spec/blob/v0.8.0/api-spec/STAC-extensions.yaml#L1144

Ex. `../2020-01-01T00:00:00Z` would query for all data from and before 2020-01-01T00:00:00Z, and `2019-12-31T23:59:59Z/..` would query for all data from and after 2019-12-31T23:59:59Z.

### Current Behaviour

400 error is returned

```
{
  "code": "400",
  "description": "Elasticsearch encountered an error executing the api."
}
```

**Comment by joshfix** [comment]
This has been on my list of things to do but haven't been able to get to it.  Thanks for the contribution!
